language: node_js

node_js:
  - '14'
  - '12'
  - '10'

cache:
  directories:
    - $HOME/.npm
    - .eslintcache

if: tag IS blank # do not build tags

install:
  - if [[ "$TRAVIS_BRANCH" = "greenkeeper/"* ]]; then npm install; else npm ci; fi

before_script:
  - greenkeeper-lockfile-update

script:
  - npm test
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - greenkeeper-lockfile-upload

jobs:
  include:
    - stage: publish
      node_js: '14'
      script: semantic-release
