language: node_js

node_js:
  - '8'
  - '6'
  - '4'

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - .eslintcache

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - npm install

script:
  - npm test
  - npm run cover

after_success:
  - test $TRAVIS_NODE_VERSION = 6 && bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: publish
      node_js: '8'
      install: npm install semantic-release
      script: skip
      after_success:
        - TRAVIS_JOB_NUMBER="WORKAROUND.1" npm run release
